### ISSUE TITLE
Different window for every node

### ISSUE THREAD

**Issue by DiskGetor** [drognisep/fynetree#8]
Hello, how to make different window for every tree node? Thank you.

**Comment by drognisep** [comment]
@DiskGetor I'm not sure I understand what you need. The tree is meant to show a collection of related tree nodes, so putting each tree node in a different window (assuming you mean a window how Fyne defines it) doesn't make a lot of sense to me because I don't know how a user would understand relationships between disparate tree nodes with such a view.

**Comment by DiskGetor** [comment]
> @DiskGetor I'm not sure I understand what you need. The tree is meant to show a collection of related tree nodes, so putting each tree node in a different window (assuming you mean a window how Fyne defines it) doesn't make a lot of sense to me because I don't know how a user would understand relationships between disparate tree nodes with such a view.

I am sorry my bad English. If add this field:
View func(w fyne.Window)fyne.CanvasObject
It will used for collection all go knowledge and any more life things

![Screenshot_20210603_222222_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/120661304-b84dce00-c4ba-11eb-9c98-a521cacf2a8c.jpg)

**Comment by DiskGetor** [comment]
func (n *nodeList) InsertSortedField(node *TreeNode) (ok bool) {
	n.mux.Lock()
	nodes := n.Objects
	for i, c := range nodes {
		if treeNode, ok1 := c.(*TreeNode); ok1 {
			if !W.Tool.Field.GetFieldNumber(node.GetModelText()) {
				return
			}
			a := W.Tool.Field.FieldNumber()
			if !W.Tool.Field.GetFieldNumber(treeNode.GetModelText()) {
				return
			}
			b := W.Tool.Field.FieldNumber()
			if a <= b {
				n.mux.Unlock()
				return W.Check.Error(n.InsertAt(i, node))
			}
		}
	}
	n.mux.Unlock()
	return W.Check.Error(n.Append(node))
}

And another advice is add sort field api like this, fynetree is work well for me now, thank you.

![Screenshot_20210603_223214_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/120662823-08796000-c4bc-11eb-9125-ff8c93882ab2.jpg)
